### ISSUE TITLE
12.26 redis-py和redis-py-cluster

### ISSUE THREAD

**Issue by vieyahn2017** [vieyahn2017/iBlog#344]
redis                            3.2.1
redis-py-cluster                 1.3.5

**Comment by vieyahn2017** [comment]
rediscluster代码如下
```python
# python std lib
import sys

# Import shortcut
from .client import StrictRedisCluster, RedisCluster
from .pipeline import StrictClusterPipeline
from .pubsub import ClusterPubSub

# Monkey patch RedisCluster class into redis for easy access
import redis
setattr(redis, "StrictRedisCluster", StrictRedisCluster)
setattr(redis, "RedisCluster", RedisCluster)
setattr(redis, "ClusterPubSub", ClusterPubSub)
setattr(redis, "StrictClusterPipeline", StrictClusterPipeline)

# Major, Minor, Fix version
__version__ = (1, 3, 5)

if sys.version_info[0:3] == (3, 4, 0):
    raise RuntimeError("CRITICAL: rediscluster do not work with python 3.4.0. Please use 3.4.1 or higher.")
```

**Comment by vieyahn2017** [comment]
版本差异报错一
```
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
>>> dir(redis)
['AuthenticationError', 'BlockingConnectionPool', 'BusyLoadingError', 'Connection', 'ConnectionError', 'ConnectionPool', 'DataError', 'InvalidResponse', 'PubSubError', 'ReadOnlyError', 'Redis', 'RedisError', 'ResponseError', 'SSLConnection', 'StrictRedis', 'TimeoutError', 'UnixDomainSocketConnection', 'VERSION', 'WatchError', '__all__', '__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__version__', '_compat', 'client', 'connection', 'exceptions', 'from_url', 'int_or_str', 'lock', 'selector', 'utils']
>>>
>>> import rediscluster
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/rediscluster/__init__.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/rediscluster/client.py", line 10, in <module>
  File "build/bdist.linux-x86_64/egg/rediscluster/connection.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/rediscluster/nodemanager.py", line 12, in <module>
ImportError: cannot import name b
>>> redis.__version__
'3.2.1'

```

**Comment by vieyahn2017** [comment]
版本差异报错二
```
> import redis
>>> dir(redis)
['AuthenticationError', 'BlockingConnectionPool', 'BusyLoadingError', 'Connection', 'ConnectionError', 'ConnectionPool', 'DataError', 'InvalidResponse', 'PubSubError', 'ReadOnlyError', 'Redis', 'RedisError', 'ResponseError', 'SSLConnection', 'StrictRedis', 'TimeoutError', 'UnixDomainSocketConnection', 'VERSION', 'WatchError', '__all__', '__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__version__', '_compat', 'client', 'connection', 'exceptions', 'from_url', 'int_or_str', 'lock', 'selector', 'utils']
>>>
>>>
>>> import rediscluster
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rediscluster/__init__.py", line 7, in <module>
    from .client import RedisCluster
  File "rediscluster/client.py", line 11, in <module>
    from .connection import (
  File "rediscluster/connection.py", line 12, in <module>
    from .nodemanager import NodeManager
  File "rediscluster/nodemanager.py", line 12, in <module>
    from redis._compat import unicode, bytes, long, basestring
ImportError: cannot import name bytes
```

**Comment by vieyahn2017** [comment]
用github上最新的redis-py-cluster，可以兼容
```
import redis
>>> dir(redis)
['AuthenticationError', 'BlockingConnectionPool', 'BusyLoadingError', 'Connection', 'ConnectionError', 'ConnectionPool', 'DataError', 'InvalidResponse', 'PubSubError', 'ReadOnlyError', 'Redis', 'RedisError', 'ResponseError', 'SSLConnection', 'StrictRedis', 'TimeoutError', 'UnixDomainSocketConnection', 'VERSION', 'WatchError', '__all__', '__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__version__', '_compat', 'client', 'connection', 'exceptions', 'from_url', 'int_or_str', 'lock', 'selector', 'utils']
>>>
>>>
>>> import rediscluster
>>>
>>> dir(redis)
['AuthenticationError', 'BlockingConnectionPool', 'BusyLoadingError', 'ClusterPipeline', 'ClusterPubSub', 'Connection', 'ConnectionError', 'ConnectionPool', 'DataError', 'InvalidResponse', 'PubSubError', 'ReadOnlyError', 'Redis', 'RedisCluster', 'RedisError', 'ResponseError', 'SSLConnection', 'StrictRedis', 'TimeoutError', 'UnixDomainSocketConnection', 'VERSION', 'WatchError', '__all__', '__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__version__', '_compat', 'client', 'connection', 'exceptions', 'from_url', 'int_or_str', 'lock', 'selector', 'utils']
```

**Comment by vieyahn2017** [comment]
## 实现Redis Cluster并实现Python链接集群
https://www.cnblogs.com/theboy/p/10690838.html

一、Redis Cluster简单介绍
二、背景
三、环境准备
3.1 主机环境
3.2 主机规划
四、部署Redis
4.1 安装Redis软件
4.2 编辑Redis配置文件
4.3 启动Redis服务
五、构建Redis Cluster集群
5.1 Redis主从复制原理
5.2 部署集群节点
5.3 创建Redis Cluster集群
5.4 集群管理
六、实现Python链接Redis Cluster集群
6.1 搭建python开发环境
6.2 安装Redis-py驱动程序
6.3 安装Redis-py-cluster驱动程序
6.4 测试API读写功能
